const wishlistsDummy = [
  {
    id: 1,
    location: "일본 나가노",
    feature: "통나무집",
    picture: "/example1.jpg",
    star: 4.92,
    price: 851243,
  },
  {
    id: 2,
    location: "한국 양평군",
    feature: "한옥",
    picture: "/example1.jpg",
    star: 4.84,
    price: 442777,
  },
  {
    id: 3,
    location: "몰디브 말레",
    feature: "보트",
    picture: "/example1.jpg",
    star: 5.0,
    price: 2611968,
  },
  {
    id: 4,
    location: "한국 인천",
    feature: "수영장",
    picture: "/example1.jpg",
    star: 4.84,
    price: 1255295,
  },
  {
    id: 5,
    location: "일본 Yufu-shi",
    feature: "료칸",
    picture: "/example1.jpg",
    star: 4.87,
    price: 380280,
  },
  {
    id: 6,
    location: "베트남 나트랑",
    feature: "사막",
    picture: "/example1.jpg",
    star: 4.92,
    price: 887039,
  },
  {
    id: 7,
    location: "베트남 나트랑",
    feature: "사막",
    picture: "/example1.jpg",
    star: 4.92,
    price: 887039,
  },
  {
    id: 8,
    location: "베트남 나트랑",
    feature: "사막",
    picture: "/example1.jpg",
    star: 4.92,
    price: 887039,
  },
  {
    id: 9,
    location: "베트남 나트랑",
    feature: "사막",
    picture: "/example1.jpg",
    star: 4.92,
    price: 887039,
  },
  {
    id: 10,
    location: "베트남 나트랑",
    feature: "사막",
    picture: "/example1.jpg",
    star: 4.92,
    price: 887039,
  },
];

export default wishlistsDummy;
